name: Test Laravel Application

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        run: npm install --no-progress

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: php artisan test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Logs
          path: ./storage/logs/*.log
